Logs for Pod: pds-tc-prometheus-server-8478cd9f99-h8hh2
ts=2023-11-28T14:30:46.247Z caller=main.go:556 level=info msg="Starting Prometheus Server" mode=server version="(version=2.41.0, branch=HEAD, revision=c0d8a56c69014279464c0e15d8bfb0e153af0dab)"
ts=2023-11-28T14:30:46.247Z caller=main.go:561 level=info build_context="(go=go1.19.4, platform=linux/amd64, user=root@d20a03e77067, date=20221220-10:40:45)"
ts=2023-11-28T14:30:46.247Z caller=main.go:562 level=info host_details="(Linux 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 pds-tc-prometheus-server-8478cd9f99-h8hh2 (none))"
ts=2023-11-28T14:30:46.247Z caller=main.go:563 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2023-11-28T14:30:46.248Z caller=main.go:564 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-11-28T14:30:46.289Z caller=web.go:559 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2023-11-28T14:30:46.299Z caller=main.go:993 level=info msg="Starting TSDB ..."
ts=2023-11-28T14:30:46.300Z caller=tls_config.go:232 level=info component=web msg="Listening on" address=0.0.0.0:9090
ts=2023-11-28T14:30:46.301Z caller=tls_config.go:235 level=info component=web msg="TLS is disabled." http2=false address=0.0.0.0:9090
ts=2023-11-28T14:30:46.340Z caller=head.go:562 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2023-11-28T14:30:46.340Z caller=head.go:606 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=10.571µs
ts=2023-11-28T14:30:46.340Z caller=head.go:612 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2023-11-28T14:30:46.345Z caller=head.go:683 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
ts=2023-11-28T14:30:46.345Z caller=head.go:720 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=1.035005ms wal_replay_duration=3.964429ms wbl_replay_duration=187ns total_replay_duration=5.038924ms
ts=2023-11-28T14:30:46.347Z caller=main.go:1012 level=warn fs_type=NFS_SUPER_MAGIC msg="This filesystem is not supported and may lead to data corruption and data loss. Please carefully read https://prometheus.io/docs/prometheus/latest/storage/ to learn more about supported filesystems."
ts=2023-11-28T14:30:46.347Z caller=main.go:1017 level=info msg="TSDB started"
ts=2023-11-28T14:30:46.347Z caller=main.go:1197 level=info msg="Loading configuration file" filename=/etc/config/prometheus.yml
ts=2023-11-28T14:30:46.355Z caller=dedupe.go:112 component=remote level=info remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="Starting WAL watcher" queue=6d8369
ts=2023-11-28T14:30:46.355Z caller=dedupe.go:112 component=remote level=info remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="Starting scraped metadata watcher"
ts=2023-11-28T14:30:46.355Z caller=dedupe.go:112 component=remote level=info remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="Replaying WAL" queue=6d8369
ts=2023-11-28T14:30:46.356Z caller=kubernetes.go:326 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-11-28T14:30:46.357Z caller=kubernetes.go:326 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-11-28T14:30:46.357Z caller=kubernetes.go:326 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-11-28T14:30:46.358Z caller=main.go:1234 level=info msg="Completed loading of configuration file" filename=/etc/config/prometheus.yml totalDuration=10.781577ms db_storage=8.176µs remote_storage=727.356µs web_handler=691ns query_engine=801ns scrape=1.343599ms scrape_sd=1.607512ms notify=1.742µs notify_sd=2.282µs rules=475.602µs tracing=16µs
ts=2023-11-28T14:30:46.358Z caller=main.go:978 level=info msg="Server is ready to receive web requests."
ts=2023-11-28T14:30:46.358Z caller=manager.go:953 level=info component="rule manager" msg="Starting rule manager..."
ts=2023-11-28T14:30:51.668Z caller=dedupe.go:112 component=remote level=info remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="Done replaying WAL" duration=5.313070074s
ts=2023-11-28T14:31:16.678Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:32:17.204Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:33:17.644Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:34:18.080Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:35:18.557Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:37:14.632Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:38:15.164Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:39:15.656Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:40:16.139Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:41:16.615Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:42:17.129Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:43:17.562Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:44:17.999Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:45:18.475Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:47:14.568Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:48:15.092Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:49:15.565Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:50:16.042Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:51:16.520Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:52:17.035Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:53:17.468Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:54:17.914Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:55:18.388Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:56:18.900Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:58:14.934Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T14:59:15.411Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T15:00:15.891Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T15:01:16.383Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T15:02:16.950Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T15:03:17.391Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T15:04:17.824Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T15:05:18.256Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T15:06:18.728Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
ts=2023-11-28T15:08:14.802Z caller=dedupe.go:112 component=remote level=error remote_name=6d8369 url=https://staging-observability.pds.portworx.com/api/v1/push msg="non-recoverable error" count=7 exemplarCount=0 err="server returned HTTP status 400 Bad Request: series has too many labels (actual: 42, limit: 40) series: 'px_volume_fs_capacity_bytes{ad_datadoghq_com_consul_check_names=\"[\\\"consul\\\"]\", ad_datadoghq_com_consul_init_configs=\"[{}]\", ad_datadoghq_com_consul_instances=\"[{\\\"url\\\": \\\"http://%host%:8500\\\", \\\"catalog_checks\\\": \\\"true\\\", \\\"self_leader_check\\\": \\\"true\\\", \\\"new_leader_checks\\\": \\\"true\\\", \\\"network_latency_checks\\\": \\\"true\\\"}]\", ad_datadoghq_com_consul_logs=\"[{\\\"source\\\": \\\"consul\\\", \\\"service\\\": \\\"con-autom-res-8229wo\\\"}]\", cluster=\"local-px-int\", clusterUUID=\"1469f4ee-e00f-458c-9fa5-303816d67578\", deployments_pds_io_pod_name=\"con-autom-res-8229wo-0\", disable_io_profile_protection=\"1\", endpoint=\"px-api\", exported_namespace=\"automation\", fg=\"false\", fs=\"ext4\", group=\"con-autom-res-8229wo-automation\", instance=\"10.13.166.62:9001\", io_profile=\"db\", job=\"portworx-service\", namespace=\"kube-system\", node=\"ip-10-13-166-62.pwx.purestorage.com\", nodeID=\"a1e6e363-6298-4d56-b6be-abe7275003ab\", pds_deployment_id=\"143eab35-6352-4786-9c81-651a1a314659\", pds_depl"
-------------------------------------
